# Generated by Django 3.2.12 on 2022-02-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('images', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('category_id', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='store.store', unique=True)),
            ],
        ),
    ]
