# Generated by Django 3.2.12 on 2022-02-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220217_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category_id',
            field=models.IntegerField(max_length=5, unique=True, verbose_name='self'),
        ),
    ]
