# Generated by Django 3.2.12 on 2022-03-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
