# Generated by Django 3.2.12 on 2022-04-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('small', models.BooleanField(default=False)),
                ('medium', models.BooleanField(default=False)),
                ('large', models.BooleanField(default=False)),
                ('extraL', models.BooleanField(default=False)),
            ],
        ),
    ]
