# Generated by Django 3.2.12 on 2022-04-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
