# Generated by Django 3.2.12 on 2022-04-18 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20220409_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 21, 34, 52, 695767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updatd_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 21, 34, 52, 695802, tzinfo=utc)),
        ),
    ]
