# Generated by Django 3.2.12 on 2022-04-18 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20220418_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 22, 43, 28, 549074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updatd_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 22, 43, 28, 549110, tzinfo=utc)),
        ),
    ]
