# Generated by Django 3.2.12 on 2022-03-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.CharField(max_length=100)),
                ('Slug', models.CharField(max_length=100)),
            ],
        ),
    ]
