# Generated by Django 3.2.12 on 2022-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220322_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
