# Generated by Django 3.2.12 on 2022-04-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220408_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
