# Generated by Django 3.2.12 on 2022-04-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique='True'),
        ),
    ]
